version: "3"
services:
  # backend 
  bio-backend:
    container_name: bio-backend
    restart: always
    build:
      context: ./Bio-Server
      dockerfile: Dockerfile.backend
    ports:
    - "3000:3000"
    depends_on: 
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/
  # DB
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27017:27017"
    volumes:
      - './mongodata:/data/db'
  # frontend
  bio-frontend:
    container_name: bio-frontend
    restart: always
    build:
      context: ./Vulgaris-Platform
      dockerfile: Dockerfile.frontend
    ports:
    - "80:80"
    volumes:
    - ./Vulgaris-Platform/default.conf:/etc/nginx/conf.d/default.conf

# services:
#   webapp:
#     build: https://github.com/mycompany/example.git#branch_or_tag:subdirectory
